### ISSUE TITLE
error on execution

### ISSUE THREAD

**Issue by cloviswarlop229** [AnatolyUss/nmig#2]
/home/dapingwing/Downloads/nmig/main.js:26
fs.readFile(__dirname + '/config.json', (error, data) => {
                                                       ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3

**Comment by AnatolyUss** [comment]
Hi!
You have to use es6 compatible version.
Which version of node.js are you using?
