### ISSUE TITLE
TypeError: done is not a function

### ISSUE THREAD

**Issue by blm14** [AnatolyUss/nmig#26]
ubuntu 12.04, node  6.3.1:

node nmig.js 

	NMIG - the database migration tool
	Copyright 2016 Anatoly Khaytovich <anatolyuss@gmail.com>
	 Boot...
	--[readDataTypesMap] Data Types Map is loaded...
	--[createLogsDirectory] Creating logs directory...
	--[createLogsDirectory] Logs directory already exists...
	--[createTemporaryDirectory] Creating temporary directory...
/root/nmig/migration/fmtp/FromMySQL2PostgreSQL.js:272
                done();
                ^

TypeError: done is not a function
    at pg.connect (/root/nmig/migration/fmtp/FromMySQL2PostgreSQL.js:272:17)
    at adjustCallback (/root/nmig/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:187:7)
    at /root/nmig/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:227:13
    at connectError (/root/nmig/node_modules/pg/lib/index.js:54:9)
    at g (events.js:286:16)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at .<anonymous> (/root/nmig/node_modules/pg/lib/client.js:121:14)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)

**Comment by AnatolyUss** [comment]
Hello,
node-pg version was changed, what led to breaking API changes.
I will update nmig as soon as possible (probably during this weekend).
Meanwhile you can update nmig's package.json in order to get older node-pg
version.

Thanks you very much for opening this issue!

**Comment by AnatolyUss** [comment]
Hello,
I've released a new version of node.
Your issue is solved.
Try latest nmig v2.1.0 (if it's still relevant).
